### ISSUE TITLE
badges and logos not showing

### ISSUE THREAD

**Issue by zarahjones** [abranhe/bigdecimal#3]
I took an  screenshot of how does the logos looks like, there is a bug there or a broken link

<img width="389" alt="screen shot 2018-10-20 at 12 16 52 am" src="https://user-images.githubusercontent.com/44123789/47251145-8cf73d00-d3fd-11e8-9574-84adc6757728.png">

**Comment by abranhe** [comment]
Thanks for reporting it, I kinda knew it because I just lost the domain of my cdn but I am updating it with a new one.

**Comment by abranhe** [comment]
Fixed on #4
